server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      encoding: utf-8
      username:
      password:
      mode: always
      data-locations:
        - classpath:db/data.sql
  jpa:
    defer-datasource-initialization: true