server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 80
spring:
  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: chaechaebing@gmail.com #앱 비밀번호 발급받은 google 계정
    password: nfzo vuhh hton xmww #발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      encoding: utf-8
      username:
      password:
      mode: always
      data-locations:
        - classpath:db/data.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    output:
      ansi:
        enabled: always
  jackson:
    serialization:
      fail-on-empty-beans: false

  h2:
    console:
      enabled: true

  logging:
    level:
      org.mybatis: DEBUG
      '[org.hibernate.type]': TRACE
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:mapper/**.xml

